config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'items#index'

  resources :items do
    collection do
      post :import_csv
    end
  end
  resources :stores do
    resources :items, only: [:new, :create]
  end
  resources :categories do
    get 'sub_categories', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :main_categories, class_name: 'Category', foreign_key: :parent_id
  belongs_to :parent, class_name: 'Category', optional: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :photo
  belongs_to :store
  belongs_to :main_category, class_name: 'Category', optional: true
  belongs_to :sub_category, class_name: 'Category', optional: true

  validate :sub_category_belongs_to_main_category
  def sub_category_belongs_to_main_category
    return if main_category.blank? || sub_category.blank?
    errors.add(:sub_category, "must belong to the selected main category") unless sub_category.main_category == main_category
  end
end

app/models/main_category.rb
class MainCategory < ApplicationRecord
  has_many :sub_categories, class_name: 'Category', foreign_key: :parent_id

end

app/models/store.rb
class Store < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :items, dependent: :destroy
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :main_category, class_name: 'MainCategory', foreign_key: :parent_id


end

app/models/user.rb
class User < ApplicationRecord
  has_many :stores
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def sub_categories
    main_category = MainCategory.find(params[:id])
    sub_categories = main_category.sub_categories

    options = sub_categories.map { |sub_category| [sub_category.name, sub_category.id] }
    render json: { options: options }
  end

end

app/controllers/items_controller.rb
# app/controllers/items_controller.rb
require 'csv'

class ItemsController < ApplicationController
  before_action :find_item, only: [:edit, :update, :destroy]

  def index
    @items = Item.where(visible: true).includes(store: :items).order("RANDOM()").limit(10)
    @categories = Item.distinct.pluck(:categories).compact.uniq
    @location = request.location.city
    if params[:query].present?
      search_query = "%#{params[:query]}%"
      @items = @items.joins(:store).where("items.name ILIKE :query OR :query = ANY(items.categories) OR items.description ILIKE :query", query: search_query)
    end

    if params[:category].present?
      @items = @items.where(":category = ANY(items.categories)", category: params[:category])
    end

    info_window_partial = if params[:query].present?
      "info_window"
    else
      "info_window_store"
    end

    @markers = @items.flat_map do |item|
      marker_html = if params[:query].present?
                      render_to_string(partial: "marker", locals: { item: item })
                    else
                      render_to_string(partial: "marker_store", locals: { item: item })
                    end

      {
        lat: item.store.latitude,
        lng: item.store.longitude,
        info_window_html: render_to_string(partial: info_window_partial, locals: { store: item.store, item: item }),
        marker_html: marker_html
      }
    end
  end

  def import_csv
    csv_file = params[:csv_file]

    if csv_file.present?
      csv_data = csv_file.read
      CSV.parse(csv_data, headers: true) do |row|
        item_params = row.to_hash
        @item = Item.new(item_params)
        @item.store = current_user.stores[0] # Set the store based on the current user
        @item.save
      end
      redirect_to store_path(current_user.stores[0]), notice: 'CSV import successful.'
    else
      redirect_to store_path(current_user.stores[0]), alert: 'Please select a CSV file.'
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to store_path(@item.store), notice: 'Item was successfully added to the stock.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to store_path(@item.store), notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to store_path(@item.store), status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :stock_quantity, :description, :store_id, :main_category_id, :sub_category_id, :visible, :pictures, :photo)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/stores_controller.rb
# app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def show
    @store = Store.find(params[:id])
    @items = @store.items.where(visible: true)
    @all_items = @store.items
    @markers = [{
      lat: @store.latitude,
      lng: @store.longitude,
      marker_html: render_to_string(partial: "marker", locals: { store: @store })
    }]
  end

  def destroy
    @store = Store.find(params[:id])
    authorize @store
    @store.destroy
    redirect_to items_path, status: :see_other
  end

  def new
    @store = current_user.stores.build
  end

  def edit
    @store = Store.find(params[:id])
    authorize @store
  end

  def index
    @stores = current_user.stores
    @markers = @stores.geocoded.map do |store|
      {
        lat: store.latitude,
        lng: store.longitude
      }
    end
  end

  def update
    @store = Store.find(params[:id])
    authorize @store
    if @store.update(store_params)
      redirect_to store_path(@store), notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @store = current_user.stores.build(store_params)
    if @store.save
      redirect_to store_path(@store)
    else
      # display the form for the user again
      render :new, status: :unprocessable_entity
    end
  end

  private
  def find_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :address, :opening_times, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/items/_csv_import_form.html.erb
<!-- app/views/items/_csv_import_form.html.erb -->
<%= form_with(url: import_csv_items_path, method: :post, multipart: true) do |form| %>
  <div class="">
    <div class="mb-4">
      <%= form.file_field :csv_file, accept: '.csv' %>
    </div>
    <div>
      <%= form.submit "Import CSV", class: "bg-green-600 p-2 rounded-md text-slate-100" %>
    </div>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= form_with model: @item, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div>
    <%= form.label :stock_quantity %>
    <%= form.number_field :stock_quantity %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :pictures %>
    <%= form.text_field :pictures %>
  </div>
  <div>
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "form-control" %>
  </div>

  <div>
    <%= form.label :main_category %>
    <%= form.collection_select :main_category, MainCategory.all, :id, :name, { include_blank: true } %>
  </div>

  <div>
    <%= form.label :sub_category %>
    <%= form.collection_select :sub_category, SubCategory.where(parent_id: @item.main_category), :id, :name, { include_blank: true } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_info_window.html.erb
<div class="px-1 rounded-md text-slate-900">
  <ul>
    <li>
      <div class="flex flex-row justify-between text-lg">
        <div><%= item.name %></div>
        <div><%= number_to_currency(item.price, unit: "€", precision: 2) %></div>
      </div>
    </li>
    <div class="flex flex-row justify-between">
      <li><%= item.description %></li>
      <li><p><%= item.stock_quantity%> x left.</p></li>
    </div>
    <div class="py-2 flex justify-center items-center">
      <li>
        <% if item.photo.attached? %>
          <%= cl_image_tag item.photo.key, height: 50, width: 40, crop: :fill %>
        <% else %>
          <%= image_tag("logos/empty.svg", class: "h-8 mr-3", alt: "icon") %>
        <% end %>
      </li>
    </div>

    <div class="flex flex-row">
      <li class="text-slate-50 bg-orange-400 w-fit px-1 rounded-md mb-1"><%= item.categories if item.categories.any?%></li>
    </div>

    <%= link_to store_path(item.store), class:"focus:outline-none no-underline" do %>
      <div class="bg-slate-50 rounded-lg p-3 shadow-lg hover:bg-orange-400 hover:text-slate-50 hover:shadow-none">
        <div class="flex flex-col justify-center items-center">
          <li class="text-lg"><%= store.name %></li>
        </div>
        <li><%= store.address %></li>
        <li><%= store.opening_times %></li>
      </div>
   <% end %>

  </ul>
</div>

app/views/items/_info_window_store.html.erb
<div class="info-window px-1 rounded-md text-slate-900">
  <ul>
    <li>
      <div class="flex flex-row justify-between">
        <div class="text-lg text-orange-400 hover:text-orange-600 focus:outline-none no-underline"><%= link_to store.name, store_path(store) %></div>
        <div><%= store.opening_times %></div>
      </div>
    </li>
    <li><p><%= store.address%></p></li>
    <li><%= store.description %></li>
    <div class="py-2 flex justify-center items-center">
      <li>
        <% if store.photo.attached? %>
          <%= cl_image_tag store.photo.key, height: 50, width: 40, crop: :fill %>
        <% else %>
          <%= image_tag("logos/empty.svg", class: "h-8 mr-3", alt: "icon") %>
        <% end %>
      </li>
    </div>

    <div class="flex flex-row">
      <% store.items.sample(3).each do |item| %>
        <div class="flex-1 py-1 px-2 mx-1 bg-slate-50 text-slate-900 rounded-md shadow-md hover:bg-orange-400 hover:text-slate-50 hover:shadow-none"><p><%= item.name %></p></div>
      <% end %>
    </div>
  </ul>
</div>

app/views/items/_marker.html.erb
<div class="bg-white rounded-lg p-3 shadow-lg">
    <p class="font-semibold"><%= item.name %></p>
    <%= number_to_currency(item.price, unit: "€", precision: 2) %>
</div>
<div class="flex items-center justify-center">
  <div><%= image_tag("logos/marker-black.svg", class: "h-8 mr-3", alt: "icon") %></div>
</div>

app/views/items/_marker_store.html.erb
<div class="flex flex-col justify-center items-center">
  <div><%= image_tag("logos/marker-black.svg", class: "h-8 mr-3", alt: "icon") %></div>
</div>

app/views/items/_new.html.erb
<%= form_with(model: @item, url: items_path, method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, step: "any", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :stock_quantity %>
    <%= form.number_field :stock_quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>


  <!-- Add other item attributes here as needed -->

  <%= form.hidden_field :store_id, value: params[:store_id] %>
  <%= form.submit "Create Item", class: "btn btn-primary" %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= render 'form' %>
<%= link_to "Back to Store", store_path(@item.store) %>

app/views/items/new.html.erb
<h2>New Item</h2>
<%= render 'new' %>
<%= link_to "Back to Store", store_path(params[:store_id]) %>

app/views/items/show.html.erb
<h1>item</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Findlocal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%# Tailwind %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%# Flowbite JS %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
    <%# Mapbox %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body class="bg-slate-50 text-slate-900">
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-orange-400 border-gray-200 dark:bg-gray-900 sticky top-0" style="z-index: 9999;">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to root_path, class:"flex items-center" do%>
        <%= image_tag("logos/Localfind1.svg", class: "h-8 mr-3", alt: "Localfind Logo") %>
        <p class="text-slate-100">Find items in stores near you</p>
    <% end %>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
    <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-orange-400 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-orange-400 dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="#" class="block py-2 pl-3 pr-4 text-white bg-orange-400 rounded md:bg-transparent md:text-white md:p-0 dark:text-white md:dark:text-blue-500 md:hover:text-orange-800" aria-current="page">Saved</a>
        </li>
        <li>
          <%= link_to "List a Store", new_store_path, class:"block py-2 pl-3 pr-4 text-slate-100 rounded hover:bg-orange-400 md:hover:bg-transparent md:border-0 md:hover:text-orange-800 md:p-0 dark:text-white md:dark:hover:text-orange-800ark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
        </li>
          <% if user_signed_in? && current_user.stores.any? %>
            <li><%= link_to "Your Store", stores_path %></li>
          <% end %>
        <li>
          <a href="#" class="block py-2 pl-3 pr-4 text-slate-100 rounded hover:bg-orange-400 md:hover:bg-transparent md:border-0 md:hover:text-orange-800 md:p-0 dark:text-white md:dark:hover:text-orange-800ark:hover:bg-gray-700 dark:hover:text-orange-800ark:hover:bg-transparent">Profile</a>
        </li>
        <li>


          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Log out of current session?"}, class: "block py-2 pl-3 pr-4 text-slate-100 rounded hover:bg-orange-400 md:hover:bg-transparent md:border-0 md:hover:text-orange-800 md:p-0 dark:text-white md:dark:hover:text-orange-800ark:hover:bg-gray-700 dark:hover:text-orange-800ark:hover:bg-transparent" %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path, class: "block py-2 pl-3 pr-4 text-slate-100 rounded hover:bg-orange-400 md:hover:bg-transparent md:border-0 md:hover:text-orange-800 md:p-0 dark:text-white md:dark:hover:text-orange-800ark:hover:bg-gray-700 dark:hover:text-orange-800ark:hover:bg-transparent" %></li>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "block py-2 pl-3 pr-4 text-slate-100 rounded hover:bg-orange-400 md:hover:bg-transparent md:border-0 md:hover:text-orange-800 md:p-0 dark:text-white md:dark:hover:text-orange-800ark:hover:bg-gray-700 dark:hover:text-orange-800ark:hover:bg-transparent" %></li>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/stores/_form.html.erb
<%= form_with(model: @store, url: stores_path, method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :opening_times %>
    <%= form.text_field :opening_times, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "form-control" %>
  </div>

  <%= form.submit%>
<% end %>

app/views/stores/new.html.erb
<h2>Create a New Store</h2>

<%= form_with(model: @store, url: stores_path, method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :opening_times %>
    <%= form.text_field :opening_times, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <%= form.submit "Create Store", class: "btn btn-primary" %>
<% end %>

<%= link_to "Home", root_path %>

app/views/stores/show.html.erb
<div class="py-10 px-20">
  <div class="flex flex-row gap-2">

    <div class="py-4 mb-5 w-2/4 flex flex-col justify-between bg-white rounded-lg shadow-md p-6">
      <div class="space-y-1">
        <div class="flex flex-row justify-between">
          <div class="text-2xl text-slate-900"><%= @store.name %></div>
          <% if policy(@store).edit? %>
            <div><%= link_to "⚙️", edit_store_path(@store) %></div>
          <% end %>
        </div>
          <% if @store.photo.attached? %>
            <div><%= cl_image_tag @store.photo.key, height: 150, width: 200, crop: :fill %></div>
          <% else %>
            <%= image_tag("logos/empty.svg", class: "h-8 mr-3", alt: "icon") %>
          <% end %>
        <div><%= @store.address %></div>
      </div>
      <div>
        <p class="font-semibold">Opening times:</p>
          <p><%= @store.opening_times %></p>
      </div>
      <div class=""><%= @store.description %></div>
    </div>

    <div class="mb-5 rounded-md" style="width: 50%; height: max; z-index: 1;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

 <div data-controller="store-show">
  <% if policy(@store).edit? %>
    <div>
      <% if @store.user == current_user %>
        <div class="flex justify-between items-center">
          <!-- Container for the buttons -->
          <div class="flex space-x-2 items-center"> <!-- Use space-x to add space between buttons -->
            <button data-action="click->store-show#showAdminList" class="bg-white p-2 rounded-lg shadow-md hover:bg-orange-400 hover:text-white">Admin</button>
            <button data-action="click->store-show#showPublicList" class="bg-white p-2 rounded-lg shadow-md hover:bg-orange-400 hover:text-white">Preview</button>
          </div>
          <div class="flex flex-row items-center"> <!-- Use items-center to vertically align items -->
            <div><%= link_to "Add Item", new_item_path(store_id: @store.id), class: "bg-white p-2 rounded-lg shadow-md hover:bg-orange-400 hover:text-white m-1" %></div>
            <div class="mt-5">
              <button data-modal-target="defaultModal" data-modal-toggle="defaultModal" class="block shadow-md m-1 bg-white hover:bg-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
                Upload CSV
              </button>
            </div>
          </div>
        </div>
      <% else %>
        <p>No items available</p>
      <% end %>
    </div>
  <% end %>



    <div class="bg-slate-100 p-4 mb-5 bg-white rounded-lg shadow-md p-6" data-target="store-show.publicList">
      <p class="font-semibold">Currently in store:</p>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">

        <% if @all_items.present? %>

          <% @items.each do |item| %>
            <div class="bg-white rounded-lg shadow-md p-4">
              <div class="flex justify-between">
                <div class="font-semibold"><%= item.name %></div>
                <div><%= number_to_currency(item.price, unit: "€", precision: 2) %></div>
              </div>

              <% if item.photo.attached? %>
                <div class="flex items-center justify-center pt-1">
                  <div><%= cl_image_tag item.photo.key, height: 100, width: 80, crop: :fill %></div>
                </div>
                <% else %>
                  <p>no photo</p>
              <% end %>

              <p class="text-gray-600"><%= item.description %></p>
              <p>Stock Quantity: <%= item.stock_quantity %></p>
            </div>
          <% end %>

      </div>
    </div>

    <% if @store.user == current_user %>
    <div class="bg-slate-100 p-4 mb-5 bg-white rounded-lg shadow-md p-6" data-target="store-show.adminList">
      <table class="w-full">
        <thead>
          <tr>
            <th class="py-2 px-4">Visibility</th>
            <th class="py-2 px-4">Photo</th>
            <th class="py-2 px-4">Name</th>
            <th class="py-2 px-4">Price</th>
            <th class="py-2 px-4">Description</th>
            <th class="py-2 px-4">Stock Quantity</th>
            <th class="py-2 px-4">Actions</th>
          </tr>
        </thead>
        <tbody>

          <% @all_items.each do |item| %>
            <tr>
              <td class="py-2 px-4 text-center"><%= item.visible? ? "◉" : "◎" %></td>
              <td class="py-2 px-4">

                <% if item.photo.attached? %>
                  <%= cl_image_tag item.photo.key, height: 50, width: 50, crop: :fill %>
                <% else %>
                  <%= image_tag("logos/empty.svg", class: "h-8 mr-3", alt: "icon") %>
                <% end %></td>

              <td class="py-2 px-4"><%= item.name %></td>
              <td class="py-2 px-4 text-center"><%= number_to_currency(item.price, unit: "€", precision: 2) %></td>
              <td class="py-2 px-4"><%= item.description %></td>
              <td class="py-2 px-4 text-center"><%= item.stock_quantity %></td>
              <td class="py-2 px-4 flex gap-2">
                <%= link_to "⚙️", edit_item_path(item), class: "bg-slate-200 p-1 rounded-md" %>
                <%= link_to "🗑️", item_path(item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bg-slate-200 p-1 rounded-md" %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>

    <div class="bg-slate-100 p-4 mb-5 bg-white rounded-lg shadow-md p-6" data-target="store-show.publicList" style="display: none;">
      <ul>

        <% @items.each do |item| %>
          <li>
            <%= item.name %> - <%= number_to_currency(item.price, unit: "€", precision: 2) %>€
          </li>
        <% end %>

      </ul>
    </div>
    <% end %>



    <div>
      <% if policy(@store).edit? %>
        <%= link_to "Delete Store", store_path(@store), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bg-red-600 p-2 mb-5 rounded-lg shadow-md text-white" %>
      <% end %>
      <%= link_to "Home", root_path, class: "bg-slate-100 p-2 mb-1 bg-white rounded-md shadow-md" %>
    </div>
  </div>
  <% else %>
    <p>No items available</p>
  <% end %>
</div>


<!-- Main modal -->
<div id="defaultModal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    Import CSV
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="defaultModal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-6 space-y-6">
              <p>Select a CSV file of your stores items and click on "Import CSV." </p>
              <%= render partial: 'items/csv_import_form' %>
            </div>
        </div>
    </div>
</div>